### ISSUE TITLE
Error upon login: FieldPath 'UTC' doesn't start with $

### ISSUE THREAD

**Issue by m-col** [electerious/Ackee#145]
I just tried to set up Ackee v2.0.0 but upon first log into the web UI (at localhost), the UI presented this error message:
```
FieldPath 'UTC' doesn't start with $
[575]</n.default@http://localhost:3000/index.js:136:141860

```

The server itself spits out this trace:
```
[Ackee] › ✖  fatal     MongoError: FieldPath 'UTC' doesn't start with $ 
    at MessageStream.messageHandler (/opt/ackee/Ackee-2.0.0/node_modules/mongodb/lib/cmap/connection.js:266:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/opt/ackee/Ackee-2.0.0/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/ackee/Ackee-2.0.0/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:710:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

This is the first time I've tried Ackee (I see there is a new release today so good timing), so it's entirely possible. I've configured something wrong. I'm running it manually with the release + `yarn` + `yarn start`.

**Comment by electerious** [comment]
I have never seen this error message before. Which version of Node.js and MongoDB do you use?

**Comment by m-col** [comment]
Both installed from debian 10 repos:
```
Package: mongodb
Version: 1:3.2.11-2+deb9u1
```
```
Package: nodejs
Version: 10.21.0~dfsg-1~deb10u1
```

**Comment by electerious** [comment]
Ackee dependents on …

Node.js (v14 or newer)
MongoDB (v4.0.6 or newer)

The error might be because the versions are too old. Let me know if this fixes the problem :)

**Comment by m-col** [comment]
My bad... installed them from their own repositories for debian and all works. Thanks!

**Comment by m-col** [comment]
My bad... installed them from their own repositories for debian and all works. Thanks!

**Comment by electerious** [comment]
Great to hear. Hope you like it! :)
