### ISSUE TITLE
Oops Something went wrong.

### ISSUE THREAD

**Issue by mzch** [electerious/Ackee#165]
I updated Ackee to 2.0.2 by `git pull` but only the following error is shown. I deleted my existing db and re-created a new one, but the same error remains.
Could anyone tell me how to fix this issue?

```
{"errors":[{"message":"Variable \"$interval\" got invalid value \"TOP\"; Value \"TOP\" does not exist in \"Interval\" enum.","locations":[{"line":2,"column":26}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}},{"message":"Variable \"$sorting\" got invalid value \"LAST_24_HOURS\"; Value \"LAST_24_HOURS\" does not exist in \"Sorting\" enum.","locations":[{"line":2,"column":48}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}},{"message":"Variable \"$range\" got invalid value \"DAILY\"; Value \"DAILY\" does not exist in \"Range\" enum.","locations":[{"line":2,"column":68}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}

Error: {"errors":[{"message":"Variable \"$interval\" got invalid value \"TOP\"; Value \"TOP\" does not exist in \"Interval\" enum.","locations":[{"line":2,"column":26}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}},{"message":"Variable \"$sorting\" got invalid value \"LAST_24_HOURS\"; Value \"LAST_24_HOURS\" does not exist in \"Sorting\" enum.","locations":[{"line":2,"column":48}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}},{"message":"Variable \"$range\" got invalid value \"DAILY\"; Value \"DAILY\" does not exist in \"Range\" enum.","locations":[{"line":2,"column":68}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}

    at n.default (https://saferepo.com/index.js:136:143740)
    at async https://saferepo.com/index.js:136:27316
```

- Node.js : v14.11.0
- yarn: 1.22.5

**Comment by electerious** [comment]
Thanks for letting me know. Working on a fix… 😰

**Comment by electerious** [comment]
I've published a new version. Should be available via Docker in 10 minutes. Let me know if that fixes the error :)

**Comment by mzch** [comment]
I confirmed 2.0.3 works well. Thanks!
