### ISSUE TITLE
Error on Ackee deployed on Vercel

### ISSUE THREAD

**Issue by kaknut** [electerious/Ackee#235]
I've earlier used previous versions of Ackee but the latest one gave me an error while logging in.

An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT

Error: An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT

    at Md (https://ackee-gamma.vercel.app/index.js:83:13349)
    at async https://ackee-gamma.vercel.app/index.js:83:13926

**Comment by electerious** [comment]
This can happen during a cold start, but it shouldn't be the norm. Was this a one time error or does it happen all the time?

**Comment by kaknut** [comment]
Happens every time, unable to log in.

**Comment by kaknut** [comment]
Fixed. The login credentials were wrong

**Comment by timshingyu** [comment]
@electerious @kaknut 
I encountered the exact same issue. Change the login credentials didn't work.
How can I debug to see what goes wrong?

**Comment by electerious** [comment]
![Vercel](https://user-images.githubusercontent.com/499088/111810282-20d2d900-88d6-11eb-9c78-0c952d95626f.png)

There should be a "View Functions Log" in your Vercel project dashboard. It should contain more details.

**Comment by timshingyu** [comment]
thx @electerious 
I got this from Function Logs

Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

Tried to use MongoDB Compress to access the DB, not successful. After changed mongodb user password, it able to access from the web and MongoDB compress.

Just weird why mongodb password got changed in the first place. 🤔
