### ISSUE TITLE
Error missing cache/leafs.json

### ISSUE THREAD

**Issue by magandrez** [electerious/Ackee#28]
Hi,

I have cloned this repo and tried to launch it as described in the documentation. `npm start` fails and, as far as I can see, there is a reference in /node/leafs.coffee to `cache/leafs.json`, but the truth is that the file (and folder) are missing. 

Any thoughts on this issue?

For my setup, please refer to the debug log below.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.3
3 info using node@v5.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Ackee@1.0.0~prestart: Ackee@1.0.0
6 silly lifecycle Ackee@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle Ackee@1.0.0~start: Ackee@1.0.0
8 verbose lifecycle Ackee@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle Ackee@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/Ackee/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle Ackee@1.0.0~start: CWD: /var/www/Ackee
11 silly lifecycle Ackee@1.0.0~start: Args: [ '-c', 'coffee ackee.coffee' ]
12 silly lifecycle Ackee@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle Ackee@1.0.0~start: Failed to exec start script
14 verbose stack Error: Ackee@1.0.0 start: `coffee ackee.coffee`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid Ackee@1.0.0
16 verbose cwd /var/www/Ackee
17 error Linux 3.2.0-4-amd64
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "start"
19 error node v5.4.1
20 error npm  v3.5.3
21 error code ELIFECYCLE
22 error Ackee@1.0.0 start: `coffee ackee.coffee`
22 error Exit status 1
23 error Failed at the Ackee@1.0.0 start script 'coffee ackee.coffee'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Ackee package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     coffee ackee.coffee
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Ackee
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Ackee
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

-Manu

**Comment by jbleuzen** [comment]
Have you a cache folder in your root folder ?
Maybe you could try create one !

I'm also thinking about the basics, you did `npm i`, `grunt`(normally done after npm post install but never know).

**Comment by electerious** [comment]
Could you try to recompile the project manually? Maybe something like `bower` is/was missing and stopped `npm i` from running `gulp`.

```sh
rm -R node_modules/
bower i
npm i
gulp
npm start
```

**Comment by magandrez** [comment]
@electerious That solved the problem. Thanks
