### ISSUE TITLE
Vercel/Serverless broken after apollo-server upgrade on develop

### ISSUE THREAD

**Issue by electerious** [electerious/Ackee#307]
**🐞 Describe the bug**

The Vercel deployment is broken after upgrading `apollo-server-lambda` to version 3 (maybe other serverless solutions are broken, too). [The code](https://github.com/electerious/Ackee/blob/develop/src/serverless.js) seems to be correct according to the [Apollo docs](https://www.apollographql.com/docs/apollo-server/deployment/lambda/), but the serverless function is throwing the following error when `/api` gets called:

```
[POST] /api
19:28:08:34
2022-01-09T18:28:10.719Z	2014d7ba-295d-4344-a94a-007608d4788b	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Unable to determine event source based on event.","stack":["Error: Unable to determine event source based on event.","    at getEventSourceNameBasedOnEvent (/var/task/node_modules/@vendia/serverless-express/src/event-sources/utils.js:88:9)","    at proxy (/var/task/node_modules/@vendia/serverless-express/src/configure.js:38:51)","    at handler (/var/task/node_modules/@vendia/serverless-express/src/configure.js:99:12)","    at Object.handler (/var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:51:27)"]}
```

**⚙️ Environment**
 - Installation: Vercel
 - Ackee version: develop

**Comment by electerious** [comment]
Related: https://github.com/apollographql/apollo-server/issues/6005

> apollo-server-lambda is designed to be run on Lambda. Vercel is not Lambda

**Comment by tkw1536** [comment]
Is there any particular reason for not staying on `apollo-server-lambda==v2.25.3` (or whatever the latest 2.x version is)?
