### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by dennisheiden** [electerious/Ackee#312]
Ackee Version: >3.1.0  (working till 3.0.6)

Error Frontend:

```
Failed to construct 'URL': Invalid URL
TypeError: Failed to construct 'URL': Invalid URL
    at https://ackee.xxx.com/index.js:13:35060
    at Array.map (<anonymous>)
    at Qv (https://ackee.xxx.com/index.js:13:35046)
    at https://ackee.xxx.com/index.js:1:158599
    at Array.map (<anonymous>)
    at https://ackee.xxx.com/index.js:1:158531
```

Error Console:

```
Error: {"errors":[{"message":"Field \"averageViews\" of type \"AverageViews!\" must have a selection of subfields. Did you mean \"averageViews { ... }\"?","locations":[{"line":6,"column":4}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"averageDuration\" of type \"AverageDuration!\" must have a selection of subfields. Did you mean \"averageDuration { ... }\"?","locations":[{"line":7,"column":4}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

    at Md (index.js:1:152785)
    at async index.js:1:158437
```

ENVs:
![image](https://user-images.githubusercontent.com/25924499/149577739-4b806526-a984-4c44-83fc-cd294909b789.png)

**Comment by electerious** [comment]
Have you updated to the latest version? Maybe the JS is still cached in the browser causing wrong requests to the API.
